############################################################################
######################         eureka 注册中心                         #######################
############################################################################

server:
  port: 8088
spring:
  application:
    name: lebo-eureka-server

security:
  basic:
    enabled: true # 启用认证
  user:
    name: lebo
    password: 123456
logging:
  level:
    root: info
  file: ./log/lebo-eureka-server.log
  
eureka:  
  instance: 
    hostname: peer1
    prefer-ip-address: true
  client: 
    serviceUrl: 
      defaultZone: http://qc:123456@localhost:8088/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false       # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 60000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）  
